import './globals.css'
import { Inter } from 'next/font/google'
import SectionTitle from '@components/sectionTitle'

import Hero from '@components/hero'
import CompaniesCarousel from '@components/Companies/CompaniesCarousel'

import Navbar2 from '@components/navbar2'
import Work from '@components/Work/Work'
import Table from '@components/Table/Table'

/* import Navbar from './components/Navbar/Navbarin'; */
import Benefits from '@components/benefits'
import { benefitOne, benefitTwo } from '../components/data'
import Video from '@components/video'
import Testimonials from '@components/testimonials'
import Cta from '@components/cta'
import Footer from '@components/footer'
import Link from 'next/link'
import Features from '@components/Features/Features'
import Simple from '@components/Simple/Simple'
import Trade from '@components/trade'
import Faq from '@components/Faq/Faq'

const inter = Inter({ subsets: ['latin'] })

/* export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
} */
	export const metadata = {
		title: 'Naas eco adventure',
	  }

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			
			<body className={inter.className}>
				<div>
					<Navbar2 />
					
					<Hero />
					<CompaniesCarousel/>
					<Work/>
					<Table/>
					<Features/>
					

					<SectionTitle
						pretitle="Nextly Benefits"
						title="Welcome to our little Nana's Asset store"
					>
						Modelos 3D Hub es una plataforma de referencia para entusiastas, diseñadores y creadores en busca de modelos 3D de alta calidad. Nuestra plataforma está construida con tecnologías avanzadas, utilizando Next.js y TailwindCSS, para brindarte una experiencia excepcional de exploración y adquisición de modelos 3D. Lo mejor de todo, es completamente de código abierto y gratuito para todos."
					</SectionTitle>
				</div>

				<div className="container mx-auto flex justify-between items-center mb-4">
					<Link href="/">
						<h3>Products Test</h3>
					</Link>
					<ul>
						<li>
							<Link href="/new" className="text-sky-500 hover:bg-sky-400">
								New
							</Link>
						</li>
					</ul>
				</div>
				<div className="flex flex-column min-h-[calc(100vh-5rem)] container mx-auto">
					{children}
				</div>

				<Benefits data={benefitOne} />
				<Benefits imgPos="right" data={benefitTwo} />
				<SectionTitle
					pretitle="Watch a video"
					title="Learn how to fullfil your needs"
				>
					This section  test 3 is to highlight a promo or demo video of your product.
					Analysts says a landing page with video has 3% more conversion rate.
					So, don&apos;t forget to add one. Just like this.
				</SectionTitle>
				<Video />
				<SectionTitle
					pretitle="Testimonials"
					title="Here's what our customers said"
				>
					Testimonails test2 is a great way to increase the brand trust and awareness.
					Use this section to highlight your popular customers.
				</SectionTitle>
				<Testimonials />
				<SectionTitle pretitle="FAQ" title="Frequently Asked Questions">
					Answer  test your customers possible questions here, it will increase the
					conversion rate as well as support or chat requests.
				</SectionTitle>
				<Simple/>
				<Trade/>
				<Faq/>
				
				{/* <Cta/> */}
				<Footer />
			</body>
		</html>
	)
}
